[package]
name = "stivium"
version = "1.0.0"
description = "Stivium - a Tauri desktop IDE shell"
authors = ["example.com"]
edition = "2021"

[lib]
name = "stivium_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
portable-pty = "0.9"
tokio = { version = "1", features = ["sync"] }

[[bin]]
name = "stivium"
path = "src/main.rs"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
